service: serverless-typescript-demo

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack

functions:
  hello:
    handler: handler.hello

    events:
     - http:
         path: hello
         method: get